
version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  mongo_data:
